### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by zychen423** [missionfission/tensorflow-wheel#1]
Hello, 
    Glad to see you release pre-compile wheel, however, when I try installing it with

`pip3.6 install tensorflow-1.9.0-cp36-cp36m-linux_x86_64.whl`

it produces the following error

```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 823, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 728, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 578, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 463, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

I guess it's because of wheel file corrupted, can you check it?
Moreover, if that's matter, I am running on a Ubuntu 18.04 with cuda-9.2 and cudnn 7.1.4, 
while the pip version is pip 18.0.

Thanks for any kind of response!

**Comment by lan2720** [comment]
@chen0423 I have the same problem.
